// A loader for the current dir

exports.authenticate = require('./authenticate')
exports.deletex = require('./deletex')
exports.getdir = require('./getdir')
exports.getstream = require('./getstream')
exports.recursivemediasearch = require('./recursivemediasearch')
exports.rename = require('./rename')
exports.stream = require('./stream')
exports.getPicture = require('./getPicture')
exports.servercheck = require('./servercheck')
exports.getFileInfo = require('./getFileInfo')
exports.getVideoThumbnail = require('./getVideoThumbnail')
exports.updateWatching = require('./updateWatching')
exports.upload = require('./upload')
exports.trycommand = require('./trycommand')